import { readFile } from "node:fs/promises";
const pkg = JSON.parse(await readFile("package.json", "utf8"));
const config = JSON.parse(await readFile("src-tauri/tauri.conf.json", "utf8"));
const cargo = await readFile("src-tauri/Cargo.toml", "utf8");
const rustVersion = cargo.match(/^version\s*=\s*"([^"]+)"/m)?.[1];
if (pkg.version !== config.version || rustVersion !== config.version) throw new Error("Package, Tauri and Rust versions must agree");
if (!/^\d+\.\d+\.\d+$/.test(config.version)) throw new Error("Only stable semantic versions can be published");
if (process.env.GITHUB_REF_TYPE === "tag" && process.env.GITHUB_REF_NAME !== `v${config.version}`) throw new Error("Tag and application version do not agree");
if (!config.plugins.updater.pubkey) throw new Error("Missing public signature key");
console.log(`Versions and public signing key verified: ${config.version}`);
